services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      CARABASSA_REPO_DIR: /data
    volumes:
      - carabassa-data:/data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "8080:80"

volumes:
  carabassa-data:
