carabassa.version=@project.version@
carabassa.api-url=${CARABASSA_API_URL:http://localhost:8080/api/}
carabassa.auth.token=${CARABASSA_TOKEN:}
carabassa.upload.threads=${CARABASSA_UPLOAD_NUM_THREADS:1}
spring.main.web-application-type=none
spring.jackson.default-property-inclusion=non-empty
spring.main.banner-mode=log